server:
  port: 8001

spring:
  application:
    name: company-ms
  data:
    mongodb:
      uri: mongodb://localhost:27017/companyDB
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest

rabbit:
  log-queue:
    name: company-logs
  log-exchange:
    name: company-logs-exchange
  log-routing:
    key: company-logs-key
  subject-queue:
    name: company-subject
  subject-exchange:
    name: company-subject-exchange
  subject-routing:
    key: company-subject-key

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
    register-with-eureka: true
    fetch-registry: true