server:
  port: 8002

spring:
  application:
    name: driver-ms
  data:
    mongodb:
      uri: mongodb://localhost:27017/driverDB
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest

rabbit:
  queue:
    name: driver-logs
  exchange:
    name: driver-logs-exchange
  routing:
    key: driver-logs-key