server:
  port: 8003

spring:
  application:
    name: log-ms
  data:
    mongodb:
      uri: mongodb://localhost:27017/logDB
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest

rabbit:
  queue:
    name: driver-logs
  exchange:
    name: driver-logs-exchange
  routing:
    key: driver-logs-key